name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'
          cache: "pnpm"

      - name: Install pnpm
        run: npm install -g pnpm

      - name: Install dependencies
        run: pnpm install

      - name: Build project
        run: pnpm build

      - name: Deploy to GitHub Pages
        if: success()
        run: |
          # Ensure the gh-pages branch exists
          git fetch origin gh-pages:gh-pages
          git worktree add docs gh-pages

          # Copy the build output to the docs folder
          rsync -av --delete build/ docs/

          # Commit and push changes to the gh-pages branch
          cd docs
          git add --all
          git commit -m "Deploy to GitHub Pages"
          git push origin gh-pages
